"""add validation_reports

Revision ID: 24cf112aebbe
Revises: 96bb3849be95
Create Date: 2026-03-07 21:40:01.247916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24cf112aebbe'
down_revision: Union[str, Sequence[str], None] = '96bb3849be95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_file_id', sa.UUID(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_file_id'], ['submission_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_reports')
    # ### end Alembic commands ###
